// This file was generated by basehub. Do not edit directly. Read more: https://basehub.com/docs/api-reference/basehub-sdk

/* eslint-disable */
/* eslint-disable eslint-comments/no-restricted-disable */
/* tslint:disable */
// @ts-nocheck

export default {
    "scalars": [
        0,
        13,
        15,
        16,
        17,
        18,
        19,
        27
    ],
    "types": {
        "AnalyticsKeyScope": {},
        "BaseRichTextJson": {
            "blocks": [
                27
            ],
            "content": [
                19
            ],
            "toc": [
                19
            ],
            "__typename": [
                27
            ]
        },
        "BlockAudio": {
            "fileName": [
                27
            ],
            "fileSize": [
                18
            ],
            "lastModified": [
                16
            ],
            "mimeType": [
                27
            ],
            "url": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "BlockCodeSnippet": {
            "allowedLanguages": [
                27
            ],
            "code": [
                27
            ],
            "html": [
                27,
                {
                    "theme": [
                        27
                    ]
                }
            ],
            "language": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "BlockColor": {
            "b": [
                18
            ],
            "g": [
                18
            ],
            "hex": [
                27
            ],
            "hsl": [
                27
            ],
            "r": [
                18
            ],
            "rgb": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "BlockDocument": {
            "_analyticsKey": [
                27,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                27
            ],
            "_idPath": [
                27
            ],
            "_slug": [
                27
            ],
            "_slugPath": [
                27
            ],
            "_sys": [
                6
            ],
            "_title": [
                27
            ],
            "on_Sarasa": [
                26
            ],
            "__typename": [
                27
            ]
        },
        "BlockDocumentSys": {
            "apiNamePath": [
                27
            ],
            "createdAt": [
                27
            ],
            "hash": [
                27
            ],
            "id": [
                17
            ],
            "idPath": [
                27
            ],
            "lastModifiedAt": [
                27
            ],
            "slug": [
                27
            ],
            "slugPath": [
                27
            ],
            "title": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "BlockFile": {
            "fileName": [
                27
            ],
            "fileSize": [
                18
            ],
            "lastModified": [
                16
            ],
            "mimeType": [
                27
            ],
            "url": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "BlockImage": {
            "alt": [
                27
            ],
            "aspectRatio": [
                27
            ],
            "fileName": [
                27
            ],
            "fileSize": [
                18
            ],
            "height": [
                18
            ],
            "lastModified": [
                16
            ],
            "mimeType": [
                27
            ],
            "placeholderURL": [
                27
            ],
            "rawUrl": [
                27
            ],
            "thumbhash": [
                27
            ],
            "url": [
                27,
                {
                    "anim": [
                        27
                    ],
                    "background": [
                        27
                    ],
                    "blur": [
                        18
                    ],
                    "border": [
                        27
                    ],
                    "brightness": [
                        18
                    ],
                    "compression": [
                        27
                    ],
                    "contrast": [
                        18
                    ],
                    "dpr": [
                        18
                    ],
                    "fit": [
                        27
                    ],
                    "format": [
                        27
                    ],
                    "gamma": [
                        27
                    ],
                    "gravity": [
                        27
                    ],
                    "height": [
                        18
                    ],
                    "metadata": [
                        27
                    ],
                    "quality": [
                        18
                    ],
                    "rotate": [
                        27
                    ],
                    "sharpen": [
                        27
                    ],
                    "trim": [
                        27
                    ],
                    "width": [
                        18
                    ]
                }
            ],
            "width": [
                18
            ],
            "__typename": [
                27
            ]
        },
        "BlockList": {
            "_analyticsKey": [
                27,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                27
            ],
            "_idPath": [
                27
            ],
            "_meta": [
                21
            ],
            "_searchKey": [
                27
            ],
            "_slug": [
                27
            ],
            "_slugPath": [
                27
            ],
            "_sys": [
                6
            ],
            "_title": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "BlockOgImage": {
            "url": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "BlockRichText": {
            "html": [
                27,
                {
                    "slugs": [
                        13
                    ],
                    "toc": [
                        13
                    ]
                }
            ],
            "json": [
                25
            ],
            "markdown": [
                27
            ],
            "plainText": [
                27
            ],
            "readingTime": [
                18,
                {
                    "wpm": [
                        18
                    ]
                }
            ],
            "__typename": [
                27
            ]
        },
        "BlockVideo": {
            "aspectRatio": [
                27
            ],
            "fileName": [
                27
            ],
            "fileSize": [
                18
            ],
            "height": [
                18
            ],
            "lastModified": [
                16
            ],
            "mimeType": [
                27
            ],
            "url": [
                27
            ],
            "width": [
                18
            ],
            "__typename": [
                27
            ]
        },
        "Boolean": {},
        "DateFilter": {
            "eq": [
                15
            ],
            "isAfter": [
                15
            ],
            "isBefore": [
                15
            ],
            "neq": [
                15
            ],
            "onOrAfter": [
                15
            ],
            "onOrBefore": [
                15
            ],
            "__typename": [
                27
            ]
        },
        "DateTime": {},
        "Float": {},
        "ID": {},
        "Int": {},
        "JSON": {},
        "ListFilter": {
            "isEmpty": [
                13
            ],
            "length": [
                18
            ],
            "__typename": [
                27
            ]
        },
        "ListMeta": {
            "totalCount": [
                18
            ],
            "__typename": [
                27
            ]
        },
        "NumberFilter": {
            "eq": [
                16
            ],
            "gt": [
                16
            ],
            "gte": [
                16
            ],
            "lt": [
                16
            ],
            "lte": [
                16
            ],
            "neq": [
                16
            ],
            "__typename": [
                27
            ]
        },
        "Query": {
            "_sys": [
                24
            ],
            "sarasa": [
                26
            ],
            "__typename": [
                27
            ]
        },
        "RepoSys": {
            "hash": [
                27
            ],
            "id": [
                17
            ],
            "slug": [
                27
            ],
            "title": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "RichTextJson": {
            "content": [
                19
            ],
            "toc": [
                19
            ],
            "on_BaseRichTextJson": [
                1
            ],
            "__typename": [
                27
            ]
        },
        "Sarasa": {
            "_analyticsKey": [
                27,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                27
            ],
            "_idPath": [
                27
            ],
            "_slug": [
                27
            ],
            "_slugPath": [
                27
            ],
            "_sys": [
                6
            ],
            "_title": [
                27
            ],
            "title": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "String": {},
        "StringFilter": {
            "contains": [
                27
            ],
            "endsWith": [
                27
            ],
            "eq": [
                27
            ],
            "matches": [
                29
            ],
            "notEq": [
                27
            ],
            "startsWith": [
                27
            ],
            "__typename": [
                27
            ]
        },
        "StringMatchesFilter": {
            "caseSensitive": [
                13
            ],
            "pattern": [
                27
            ],
            "__typename": [
                27
            ]
        }
    }
}