// This file was generated by basehub. Do not edit directly. Read more: https://basehub.com/docs/api-reference/basehub-sdk

/* eslint-disable */
/* eslint-disable eslint-comments/no-restricted-disable */
/* tslint:disable */
// @ts-nocheck

export declare const BranchSwitcher: ({ isForcedDraft, draft, }: {
    isForcedDraft: boolean;
    draft: boolean;
}) => import("react/jsx-runtime").JSX.Element;
