// This file was generated by basehub. Do not edit directly. Read more: https://basehub.com/docs/api-reference/basehub-sdk

/* eslint-disable */
/* eslint-disable eslint-comments/no-restricted-disable */
/* tslint:disable */
// @ts-nocheck

import * as React from "react";
export declare const ClientConditionalRenderer: ({ draft, isForcedDraft, enableDraftMode, disableDraftMode, }: {
    draft: boolean;
    isForcedDraft: boolean;
    enableDraftMode: (bshbPreviewToken: string) => Promise<{
        status: number;
        response: object;
    }>;
    disableDraftMode: () => Promise<void>;
}) => React.ReactPortal | null;
