// This file was generated by basehub. Do not edit directly. Read more: https://basehub.com/docs/api-reference/basehub-sdk

/* eslint-disable */
/* eslint-disable eslint-comments/no-restricted-disable */
/* tslint:disable */
// @ts-nocheck

export declare const ClientToolbar: ({ draft, isForcedDraft, enableDraftMode, disableDraftMode, bshbPreviewToken, shouldAutoEnableDraft, seekAndStoreBshbPreviewToken, }: {
    draft: boolean;
    isForcedDraft: boolean;
    enableDraftMode: (bshbPreviewToken: string) => Promise<{
        status: number;
        response: object;
    }>;
    disableDraftMode: () => Promise<void>;
    bshbPreviewToken: string;
    shouldAutoEnableDraft: boolean | undefined;
    seekAndStoreBshbPreviewToken: (type?: "url-only") => string | undefined;
}) => import("react/jsx-runtime").JSX.Element;
